"""Behavioral tests for the drift-check helper scripts."""

from __future__ import annotations

import contextlib
import io
import typing as _t

import pytest

from tox_plugins.lock._check_compare import main as compare_locks
from tox_plugins.lock._check_seed import main as seed_scratch
from tox_plugins.lock._plugin import (
    _CHECK_COMPARE_SCRIPT,
    _CHECK_SEED_SCRIPT,
)


if _t.TYPE_CHECKING:
    from collections import abc as _c
    from pathlib import Path


class _ScriptResult(_t.NamedTuple):
    """What running one of the scripts leaves behind."""

    returncode: int
    stderr: str


def _run(
    script_main: _c.Callable[[_c.Sequence[str]], int],
    *args: Path,
) -> _ScriptResult:
    """Run one of the plugin's scripts the way the env would.

    Called rather than spawned: the scripts run under the lock env's
    interpreter in production, which the test suite has no business
    building, and an in-process call measures the coverage of code
    that ships in the wheel like any other module.

    :param script_main: The entry point of the script to run.
    :param args: The paths to pass to the script.
    :returns: The exit code it left with and what it wrote to stderr.
    """
    stderr = io.StringIO()
    with contextlib.redirect_stderr(stderr):
        returncode = script_main([str(arg) for arg in args])

    return _ScriptResult(returncode, stderr.getvalue())


@pytest.mark.parametrize(
    'script',
    (_CHECK_SEED_SCRIPT, _CHECK_COMPARE_SCRIPT),
    ids=lambda script: str(script.name),
)
def test_the_check_scripts_ship_beside_the_plugin(script: Path) -> None:
    """The commands name a file that is actually installed.

    Nothing imports either script -- the check env runs them by path,
    from wherever the dist was installed -- so a packaging change
    dropping them would surface as a failing `lock-deps-check` in a
    project rather than here.

    :param script: The script path the plugin builds its command from.
    """
    assert script.is_file()


def test_seed_copies_the_lock_into_a_missing_directory(tmp_path: Path) -> None:
    """The scratch copy brings its parent directory along.

    :param tmp_path: Pytest's temporary directory fixture.
    """
    lock_file = tmp_path / 'requirements.txt'
    lock_file.write_text('attrs==1.0\n', encoding='utf-8')
    scratch_file = tmp_path / 'nested' / 'scratch' / 'requirements.txt'

    assert _run(seed_scratch, lock_file, scratch_file).returncode == 0
    assert scratch_file.read_text(encoding='utf-8') == 'attrs==1.0\n'


def test_seed_clears_a_scratch_file_left_by_an_earlier_run(
    tmp_path: Path,
) -> None:
    """A lock that is not there yet leaves no stale scratch to compare.

    :param tmp_path: Pytest's temporary directory fixture.
    """
    scratch_file = tmp_path / 'requirements.txt'
    scratch_file.write_text('attrs==1.0\n', encoding='utf-8')

    seed_result = _run(
        seed_scratch,
        tmp_path / 'absent.txt',
        scratch_file,
    )

    assert seed_result.returncode == 0
    assert not scratch_file.exists()


@pytest.mark.parametrize(
    ('scratch_text', 'lock_text', 'expected_failure'),
    (
        pytest.param('attrs==1.0\n', 'attrs==1.0\n', False, id='in-sync'),
        pytest.param('attrs==2.0\n', 'attrs==1.0\n', True, id='pin-moved'),
        pytest.param(
            'attrs==1.0\nidna==3.0\n',
            'attrs==1.0\n',
            True,
            id='dependency-added',
        ),
        pytest.param(
            '# This file was autogenerated by uv via the following '
            'command:\n#    tox run -e lock-deps\nattrs==1.0\n',
            '# This file was autogenerated by uv via the following '
            'command:\n#    tox run -e lock-deps\nattrs==1.0\n',
            False,
            id='the-header-both-envs-seed-is-the-same-header',
        ),
        pytest.param(
            '# uv pip compile -o /tmp/scratch.txt\nattrs==1.0\n',
            '# uv pip compile -o requirements.txt\nattrs==1.0\n',
            True,
            id='a-header-the-envs-would-not-write-is-drift',
        ),
        pytest.param(
            'attrs==1.0\n    # via -r requirements/test.in\n',
            'attrs==1.0\n    # via -r requirements/base.in\n',
            True,
            id='annotations-moving-while-the-pins-hold-still',
        ),
    ),
)
def test_compare_reports_drift(
    *,
    tmp_path: Path,
    scratch_text: str,
    lock_text: str,
    expected_failure: bool,
) -> None:
    """Anything recompiling would change fails the check.

    :param tmp_path: Pytest's temporary directory fixture.
    :param scratch_text: The contents of the freshly compiled lock.
    :param lock_text: The contents of the lock the project committed.
    :param expected_failure: Whether the comparison should fail.
    """
    scratch_file = tmp_path / 'scratch.txt'
    scratch_file.write_text(scratch_text, encoding='utf-8')
    lock_file = tmp_path / 'requirements.txt'
    lock_file.write_text(lock_text, encoding='utf-8')

    compare_result = _run(compare_locks, scratch_file, lock_file)

    assert bool(compare_result.returncode) is expected_failure
    if expected_failure:
        assert 'out of date' in compare_result.stderr


def test_compare_fails_when_there_is_no_lock_to_compare(
    tmp_path: Path,
) -> None:
    """A project that never locked gets told so, not a traceback.

    :param tmp_path: Pytest's temporary directory fixture.
    """
    scratch_file = tmp_path / 'scratch.txt'
    scratch_file.write_text('attrs==1.0\n', encoding='utf-8')

    compare_result = _run(
        compare_locks,
        scratch_file,
        tmp_path / 'requirements.txt',
    )

    assert compare_result.returncode
    assert 'does not exist' in compare_result.stderr
    assert 'Traceback' not in compare_result.stderr


def test_compare_shows_which_pins_moved(tmp_path: Path) -> None:
    """A failing check names the drift instead of merely asserting it.

    :param tmp_path: Pytest's temporary directory fixture.
    """
    scratch_file = tmp_path / 'scratch.txt'
    scratch_file.write_text(
        '# header\nattrs==2.0\nidna==3.0\n',
        encoding='utf-8',
    )
    lock_file = tmp_path / 'requirements.txt'
    lock_file.write_text('# header\nattrs==1.0\n', encoding='utf-8')

    compare_result = _run(compare_locks, scratch_file, lock_file)

    assert compare_result.returncode
    assert '-attrs==1.0' in compare_result.stderr
    assert '+attrs==2.0' in compare_result.stderr
    assert '+idna==3.0' in compare_result.stderr
    # NOTE: The diff covers what was compared, and a line both files
    # NOTE: agree on is context rather than drift -- so the header is
    # NOTE: there unsigned, telling a reader nothing moved in it.
    assert ' # header' in compare_result.stderr


def test_compare_reports_every_stale_lock_in_one_run(tmp_path: Path) -> None:
    """One invocation covers all the locks, not just the first one.

    ``commands`` stop at the first failure, so a comparison per lock
    would report the earliest stale one and say nothing about the rest
    -- turning a single red build into as many as there are locks
    behind it.

    :param tmp_path: Pytest's temporary directory fixture.
    """
    pairs: list[Path] = []
    lock_files: list[Path] = []
    for lock_name, pin in (('base.txt', 'attrs'), ('test.txt', 'idna')):
        scratch_file = tmp_path / f'scratch-{lock_name}'
        scratch_file.write_text(f'{pin}==2.0\n', encoding='utf-8')
        lock_file = tmp_path / lock_name
        lock_file.write_text(f'{pin}==1.0\n', encoding='utf-8')
        pairs += [scratch_file, lock_file]
        lock_files.append(lock_file)

    compare_result = _run(compare_locks, *pairs)

    assert compare_result.returncode
    assert '-attrs==1.0' in compare_result.stderr
    assert '-idna==1.0' in compare_result.stderr
    both_locks = ', '.join(map(str, lock_files))
    assert f'{both_locks} are out of date' in compare_result.stderr


def test_compare_leaves_the_locks_that_are_current_out_of_it(
    tmp_path: Path,
) -> None:
    """A lock still matching its sources is not named as drifted.

    :param tmp_path: Pytest's temporary directory fixture.
    """
    current_scratch = tmp_path / 'scratch-current.txt'
    current_scratch.write_text('attrs==1.0\n', encoding='utf-8')
    current_lock = tmp_path / 'current.txt'
    current_lock.write_text('attrs==1.0\n', encoding='utf-8')
    stale_scratch = tmp_path / 'scratch-stale.txt'
    stale_scratch.write_text('idna==2.0\n', encoding='utf-8')
    stale_lock = tmp_path / 'stale.txt'
    stale_lock.write_text('idna==1.0\n', encoding='utf-8')

    compare_result = _run(
        compare_locks,
        current_scratch,
        current_lock,
        stale_scratch,
        stale_lock,
    )

    assert compare_result.returncode
    assert f'{stale_lock} is out of date' in compare_result.stderr
    assert 'current.txt' not in compare_result.stderr
