"""Write the requirements file a build backend's lock is compiled from.

Run by path, under the lock env's own interpreter, rather than
imported -- see :mod:`tox_plugins.lock._check_seed` for why the
standard library is all there is here.

Nothing is parsed here. The requirements arrive on the command line,
read out of ``[build-system] requires`` by the plugin that assembled
it: that table is TOML, and ``tomllib`` is only in the standard
library from 3.11 while this plugin supports older interpreters --
whereas the plugin itself runs under ``tox``, which carries a parser
either way.
"""

from __future__ import annotations

import sys
import typing as _t
from pathlib import Path


if _t.TYPE_CHECKING:
    from collections import abc as _c


# NOTE: The source is on a line of its own so that the header keeps
# NOTE: its shape whatever the file is called -- a name wrapped into
# NOTE: the prose below it would reflow the comment, and the check
# NOTE: compares every line.
_HEADER = """\
# Generated by tox-lock from the `[build-system] requires` table of
# {source}
# Edit that table rather than this file -- `tox run -e lock-deps-check`
# reports the two drifting apart.
"""


def main(args: _c.Sequence[str]) -> int:
    """Mirror a ``[build-system] requires`` table into a source file.

    ``uv pip compile`` reads a project's ``[project] dependencies``
    from ``pyproject.toml`` and has no option asking it for the other
    table, so the lock pinning a build backend is compiled out of a
    mirror of it. Writing that mirror rather than leaving it to the
    project is what keeps a requirement added to the table from going
    on being resolved against the index because the copy was not
    touched.

    The file is written whole on every run, so an entry dropped from
    the table leaves the mirror the same way one added to it arrives.

    :param args: The file to write, the source it is named after, then
        the requirements themselves.
    :returns: The exit code to leave with.
    """
    target, source, *requirements = args
    target_file = Path(target)
    target_file.parent.mkdir(parents=True, exist_ok=True)
    target_file.write_text(
        _HEADER.format(source=source) + ''.join(
            f'{requirement}\n' for requirement in requirements
        ),
        encoding='utf-8',
    )
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
